In [1]:
print("hello")

hello


In [1]:
import pickle 
import numpy as np

In [32]:
#filename = "C-sin_10-shot_legit_2.p"
#filename = "C-sin_10-shot_legit_stateform.p"
filename = "bounce-states_100-shot_2.p"
#filename = "bounce-images_100-shot.p"
tasks = pickle.load(open(filename, "rb"))

In [33]:
firstTask = tasks['tasks_train'][0]
data_firstTask = firstTask[0]
info_firstTask = firstTask[1]
traina = data_firstTask[0]
trainb = data_firstTask[1]
inputa = traina[0]
labela = traina[1]

inputb = trainb[0]
labelb = trainb[1]

In [34]:
len(traina[0])
print(len(tasks['tasks_train']))
print(len(tasks['tasks_test']))
print(len(firstTask))
print(len(firstTask[0]))
print(firstTask[1])
print(len(traina))
print(len(trainb))
print(len(inputa))
print(len(inputb))
print(inputa[0].shape)
print(inputb[1].shape)
print(labela[0].shape)
print(labelb[0].shape)

100
1000
2
2
{u'z': array([ 5.43156591, 10.3998514 , 23.3517287 , 13.24550813, 23.82431626,
       32.24375273,  8.19451581, 28.64767152])}
2
2
100
100
(3, 2)
(3, 2)
(10, 2)
(10, 2)


In [7]:
ina_new = np.tile(inputa,(10,3,2))

In [26]:
print(inputa.shape)
print(ina_new.shape)
print(labela.shape)
print(inputb.ravel())

(10, 1)
(10, 30, 2)
(10, 1)
[ 0.86400986 -4.93738031 -2.74120474 -2.20810604 -1.00739515 -1.43184173
 -0.14290087 -3.46777463  4.95875311 -1.11199522]


In [28]:
c = np.array([[1],[2],[3],[4]])
print(c)
print(c.ravel())

[[1]
 [2]
 [3]
 [4]]
[1 2 3 4]


In [48]:
c = inputa
print(c.shape)
np.tile(c.ravel(),(6,1)).transpose().reshape(-1,3,2).shape

(10, 1)


(10, 3, 2)

In [18]:
print(c.shape)

(4, 1)


In [26]:
boxCords = info['z'].reshape(-1,2)*.025
            xCords = list(boxCords[:,0])
            yCords = list(boxCords[:,1])
            #Add last element to it.
            xCords.append(xCords[0])
            yCords.append(yCords[0])
            if shouldPlot:
                plt.plot(xCords,yCords)
            inputa = data[0][0].reshape(-1,6)

IndentationError: unexpected indent (<ipython-input-26-0f0546e2e6bb>, line 2)

In [97]:
task = firstTask

In [102]:
data = task[0]
info = task[1]
boxCords = info['z'].reshape(-1,2)*.025
xCords = list(boxCords[:,0])
yCords = list(boxCords[:,1])
#Add last element to it.
xCords.append(xCords[0])
yCords.append(yCords[0])
inputa = data[0][0][0]
print(inputa.shape)
#inputa = data[0][0].reshape(-1,6)

(3, 2)


In [39]:
print(inputa.shape)

(100, 6)


In [43]:
val = data[0][0][0]
print(val)

[[0.25312698 0.64237946]
 [0.22848836 0.6907153 ]
 [0.3200658  0.72145456]]


In [63]:
print(val)
val = val.reshape(3,-1,1)
print(val.shape)
newval = np.tile(val,(1,1,2))
print(newval.shape)
print(newval)

[[[0.25312698]
  [0.64237946]]

 [[0.22848836]
  [0.6907153 ]]

 [[0.3200658 ]
  [0.72145456]]]
(3, 2, 1)
(3, 2, 2)
[[[0.25312698 0.25312698]
  [0.64237946 0.64237946]]

 [[0.22848836 0.22848836]
  [0.6907153  0.6907153 ]]

 [[0.3200658  0.3200658 ]
  [0.72145456 0.72145456]]]


In [81]:
task[0][0][0].shape
task[0][0][0][0]

array([[0.25312698, 0.64237946],
       [0.22848836, 0.6907153 ],
       [0.3200658 , 0.72145456]], dtype=float32)

In [79]:
newval = task[0][0][0].reshape(-1,3,2,1)
newval.shape

(100, 3, 2, 1)

In [80]:
data[0][1][:,0:1,:]
fin.shape

(100, 3, 2, 2)

In [82]:
fin[0]

array([[[0.25312698, 0.25312698],
        [0.64237946, 0.64237946]],

       [[0.22848836, 0.22848836],
        [0.6907153 , 0.6907153 ]],

       [[0.3200658 , 0.3200658 ],
        [0.72145456, 0.72145456]]], dtype=float32)

In [87]:
data[0][1][:,0:1,:].reshape(-1,1,2,1).shape

(100, 1, 2, 1)

In [90]:
np.tile(data[0][1][:,0:1,:].reshape(-1,1,2,1),(1,1,1,2)).shape

(100, 1, 2, 2)

In [91]:
fin.shape

(100, 3, 2, 2)

In [113]:
inputs = np.vstack((fin,fin))
inputs = inputs.reshape(1,-1,3,2,2)

In [114]:
inputs.shape

(1, 200, 3, 2, 2)

In [100]:
data = task[0]

In [107]:
print(data[0][0].shape)

(100, 3, 2)


In [109]:
data = task[0]
info = task[1]
boxCords = info['z'].reshape(-1,2)*.025
xCords = list(boxCords[:,0])
yCords = list(boxCords[:,1])
#Add last element to it.
xCords.append(xCords[0])
yCords.append(yCords[0])
inputa = data[0][0].reshape(-1,6) # This is doing exactly what we want
onlyNextLabela = data[0][1][:,0:1,:].reshape(-1,2)
inputb = data[1][0].reshape(-1,6)
onlyNextLabelb = data[1][1][:,0:1,:].reshape(-1,2) #This was pulling from the same set. 
inputs = np.vstack((inputa,inputb))
inputs = inputs.reshape(1,-1,6)
labels = np.vstack((onlyNextLabela,onlyNextLabelb)).reshape(1,-1,2)

In [110]:
inputa.shape

(100, 6)

In [111]:
inputb.shape

(100, 6)

In [112]:
inputs.shape

(1, 200, 6)