In [1]:
print("hello")

hello


In [9]:
import pickle 
import numpy as np

In [10]:
#filename = "C-sin_10-shot_legit_2.p"
#filename = "C-sin_10-shot_legit_stateform.p"
#filename = "bounce-states_100-shot_2.p"
filename = "bounce-images_100-shot-2.p"
tasks = pickle.load(open(filename, "rb"))

In [11]:
firstTask = tasks['tasks_train'][0]
data_firstTask = firstTask[0]
info_firstTask = firstTask[1]
traina = data_firstTask[0]
trainb = data_firstTask[1]
inputa = traina[0]
labela = traina[1]
inputb = trainb[0]
labelb = trainb[1]

In [12]:
len(traina[0])
print(len(tasks['tasks_train']))
print(len(tasks['tasks_test']))
print(len(firstTask))
print(len(firstTask[0]))
print(firstTask[1])
print(len(traina))
print(len(trainb))
print(len(inputa))
print(len(inputb))
print(inputa[0].shape)
print(inputb[1].shape)
print(labela[0].shape)
print(labelb[0].shape)

100
100
2
2
{u'z': array([ 6.3037904 ,  5.735268  , 28.48628753,  4.88740787, 33.36295815,
       29.84352735, 11.70521981, 24.32233826])}
2
2
100
100
(3, 39, 39)
(3, 39, 39)
(10, 39, 39)
(10, 39, 39)


In [7]:
ina_new = np.tile(inputa,(10,3,2))=

In [26]:
print(inputa.shape)
print(ina_new.shape)
print(labela.shape)
print(inputb.ravel())

(10, 1)
(10, 30, 2)
(10, 1)
[ 0.86400986 -4.93738031 -2.74120474 -2.20810604 -1.00739515 -1.43184173
 -0.14290087 -3.46777463  4.95875311 -1.11199522]


In [28]:
c = np.array([[1],[2],[3],[4]])
print(c)
print(c.ravel())

[[1]
 [2]
 [3]
 [4]]
[1 2 3 4]


In [48]:
c = inputa
print(c.shape)
np.tile(c.ravel(),(6,1)).transpose().reshape(-1,3,2).shape

(10, 1)


(10, 3, 2)

In [17]:
print(inputa[0])

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [18]:
print(inputa)

[[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
 

In [19]:
firstTask = tasks['tasks_train'][0]
data_firstTask = firstTask[0]
info_firstTask = firstTask[1]
traina = data_firstTask[0]
trainb = data_firstTask[1]
inputa = traina[0]
labela = traina[1]
inputb = trainb[0]
labelb = trainb[1]

In [20]:
data = data_firstTask

In [21]:
info = info_firstTask

In [22]:
print(info)

{u'z': array([ 6.3037904 ,  5.735268  , 28.48628753,  4.88740787, 33.36295815,
       29.84352735, 11.70521981, 24.32233826])}


In [25]:
data[0][0][0].shape

(3, 39, 39)

In [1]:
data[0]

NameError: name 'data' is not defined

In [3]:
import numpy as np
test_val = np.random.rand(1,100,3,2,2)
print(test_val.shape)

(1, 100, 3, 2, 2)


In [15]:
test_val[:,:,0:1,:,:]

array([[[[[0.53516995, 0.9972768 ],
          [0.91312222, 0.02484109]]],


        [[[0.66124919, 0.0590206 ],
          [0.84983278, 0.63239868]]],


        [[[0.66736837, 0.25537648],
          [0.03877603, 0.52375815]]],


        [[[0.64190598, 0.04359728],
          [0.30007444, 0.36492433]]],


        [[[0.75741781, 0.50399142],
          [0.5714327 , 0.67686377]]],


        [[[0.49101969, 0.87922045],
          [0.82839214, 0.28052412]]],


        [[[0.40669906, 0.53056553],
          [0.25603547, 0.22763492]]],


        [[[0.65194015, 0.39885742],
          [0.02590691, 0.81785311]]],


        [[[0.59770717, 0.15685925],
          [0.53237469, 0.0628506 ]]],


        [[[0.72969184, 0.15407238],
          [0.97099248, 0.33532068]]],


        [[[0.55593239, 0.23972975],
          [0.39858548, 0.24292776]]],


        [[[0.96014908, 0.72958519],
          [0.69024064, 0.27551289]]],


        [[[0.52949452, 0.52988429],
          [0.95169137, 0.39509679]]],


        [[[0

In [7]:
test_val[:,:,1:2,:,:].shape

(1, 100, 1, 2, 2)

In [17]:
test_val[:,:,2:3,:,:]

array([[[[[0.63492176, 0.96375518],
          [0.05801455, 0.75731502]]],


        [[[0.70010234, 0.0507889 ],
          [0.37188103, 0.11519384]]],


        [[[0.32843921, 0.80253741],
          [0.36030711, 0.69371365]]],


        [[[0.46861265, 0.15044623],
          [0.20168352, 0.83951315]]],


        [[[0.02301949, 0.4573435 ],
          [0.30604486, 0.87583537]]],


        [[[0.51385402, 0.09292967],
          [0.71886973, 0.16949572]]],


        [[[0.76845161, 0.78654417],
          [0.52959829, 0.34934635]]],


        [[[0.76975802, 0.86638659],
          [0.97654766, 0.82996767]]],


        [[[0.9458453 , 0.38042735],
          [0.65636641, 0.47344981]]],


        [[[0.17905064, 0.09847014],
          [0.39231275, 0.61002724]]],


        [[[0.46137673, 0.47663215],
          [0.86305382, 0.30913195]]],


        [[[0.67390677, 0.78044475],
          [0.78967274, 0.69859085]]],


        [[[0.99257443, 0.73778555],
          [0.95627416, 0.34343704]]],


        [[[0